# Generated by Django 5.0.6 on 2024-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_footer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/company/')),
            ],
        ),
        migrations.AddField(
            model_name='footer',
            name='img',
            field=models.ManyToManyField(to='home_app.imagecompany', verbose_name='عکس های شرکت'),
        ),
    ]
