# Generated by Django 5.0.6 on 2024-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0017_subshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم نویسنده'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='author_phone',
            field=models.CharField(default='matin', max_length=255, verbose_name='نویسنده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreview',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نویسنده'),
        ),
    ]
