# Generated by Django 5.0.6 on 2024-08-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0018_productreview_author_name_productreview_author_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='author',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='author_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نویسنده'),
        ),
    ]
