# Generated by Django 5.0.6 on 2024-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0014_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
