# Generated by Django 5.0.6 on 2024-08-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0015_alter_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.TextField(),
        ),
    ]
