# Generated by Django 5.0.6 on 2024-08-20 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0016_alter_address_address_alter_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن معتبر نیست', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
